# Generated by Django 4.1 on 2023-03-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='quiz_picture/'),
        ),
        migrations.AlterModelTable(
            name='choices',
            table='choices',
        ),
    ]
