# Generated by Django 4.1 on 2023-03-20 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0002_alter_choices_description_alter_quiz_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='解説文(任意)'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='正誤(チェックを入れると正解として扱われます)'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz', verbose_name='対応するクイズ'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='sentence',
            field=models.CharField(max_length=10, verbose_name='選択肢(必須)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者名'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='quiz_picture/', verbose_name='写真(任意)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='sentence',
            field=models.CharField(max_length=100, verbose_name='問題文(必須)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=20, verbose_name='タイトル(必須)'),
        ),
    ]
