# Generated by Django 4.1 on 2023-03-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_choices_description_alter_choices_is_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='picture',
        ),
    ]
