# Generated by Django 4.1 on 2023-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_remove_quiz_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='解説文'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='sentence',
            field=models.CharField(max_length=10, verbose_name='選択肢'),
        ),
    ]
